### ISSUE TITLE
Changing source of named imports

### ISSUE THREAD

**Issue by tadeuszwojcik** [suchipi/transform-imports#3]
Hi,
First of all, thanks for publishing this package, it makes transforming imports really easy.
In my case I simply need to replace:

`import {Foo, Bar} from 'a';`
to
`import {Foo, Bar} from 'b';`
using `transform-imports` for that it works great, but I get:
`import {Foo} from 'b';`
`import {Bar} from 'b';`

I know it's described in readme and works as intended, but perhaps there is a way using existing API to achieve what I'd ideally want?

Another minor things is that I get line endings replaced from \n to \r\n (I'm on Windows) but I guess it's `recast` thing.

**Comment by suchipi** [comment]
Unfortunately no, due to the way I designed the API, this isn't possible :\\ I wish I had thought of this back then.

I think your best bet is to dive into your node_modules folder and comment out [this line](https://github.com/suchipi/transform-imports/blob/338505a93a121ae9ae671dfeb5cb6b6642f38341/packages/imports-visitor/src/ImportDefinition.js#L86) in `node_modules/imports-visitor/dist/ImportDefinition.js`. This might break some other stuff, but as long as you are only changing some named imports in your code, it should work.

The only way would be to write a babel plugin to find and combine the import statements after-the-fact.

**Comment by tadeuszwojcik** [comment]
Thank you! much appreciated! Finally I went with babel plugin route, hope will have opportunity to use this awesome lib for other scenarios. Have a nice day! Thanks.
